### ISSUE TITLE
Inconsistent collision detection

### ISSUE THREAD

**Issue by marconett** [britzl/platypus#23]
With moving platforms, collision detection can be very inconsistent, resulting the character moving into platforms and being warped out of platforms when collision is detected too late.

![go1](https://user-images.githubusercontent.com/3315507/92595593-e80dd380-f2a4-11ea-8fbd-6b874e0483a8.gif)
![go2](https://user-images.githubusercontent.com/3315507/92595594-e80dd380-f2a4-11ea-82de-428bf38bbb33.gif)

I played around with adding more rays, but that does only help a little:
![g1](https://user-images.githubusercontent.com/3315507/92595627-f78d1c80-f2a4-11ea-993e-e5f7d09e7168.gif)
![g2](https://user-images.githubusercontent.com/3315507/92595628-f8be4980-f2a4-11ea-872e-aaacba184ef8.gif)

Adding even more rays in between, the character get's caught up on platforms even easier.

**Comment by britzl** [comment]
I pushed a new version with up-left and up-right raycasts which according to my own testing solves the problem. Please give it a try!

**Comment by marconett** [comment]
Thank you!

The character now does not get caught on or clips into platforms when jumping at them from below. However, the issue seen in the very first gif and other similar ones are still present.

**Comment by britzl** [comment]
> However, the issue seen in the very first gif and other similar ones are still present.

This seems to happen when it is only the down-left/right ray that hits the platform right? At least that's what it looks like from the gif.

**Comment by marconett** [comment]
> This seems to happen when it is only the down-left/right ray that hits the platform right? At least that's what it looks like from the gif.

Yes, that seems to be the case. Here's a video with three different examples of this happening: https://www.youtube.com/watch?v=uHpuQ5_5ytQ

**Comment by britzl** [comment]
I've fixed this last case now in the latest release
